
 [

{
		"id" : "0001",
		"firstname": "Model",
		"lastname": "1",
		"fullname": "Model 1",
		"image": "model1",
        "showthumbnail":true,
        "thumbnail": ["model1", "model2", "model3", "model4"],
        "imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage": ["http://www.google.com", "http://www.yahoo.com", "http://www.bing.com", "http://www.google.com"],
		"dob" : "09/15/1985",
		"team": "NA",
		"position": "Goalkeeper",
		"city": "Fresno",
		"divpics":"hello world 1",
		"qrcode": "website-model1",
		"paragraph1": "Jesse Zamudio Biography is here to stay, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought"

	},
	{
		"id" : "0002",
		"firstname": "Model",
		"lastname": "2",
		"fullname": "Model 2",
		"image": "model2",
		"showthumbnail": true,
		"thumbnail": ["model1", "model2", "model3", "model4"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "11/07/1990",
		"team": "NA",
		"position": "Goalkeeper/Striker",
		"city": "Fresno",
		"divpics":"hello world 2",
		"qrcode": "website-model2",
		"paragraph1": "Andres Zamudio was here, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0003",
		"firstname": "Model",
		"lastname": "3",
		"fullname": "Model 3",
		"image": "model3",
		"showthumbnail": true,
		"thumbnail": ["model1", "model2", "model3", "model4"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "Center-Back Defender",
		"city": "Madera",
		"divpics":"hello world 3",
		"qrcode": "website-model3",
		"paragraph1": "Chato Ramos defiende al , Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0004",
		"firstname": "Model",
		"lastname": "4",
		"fullname": "Model 4",
		"image": "model4",
		"showthumbnail": true,
		"thumbnail": ["model1", "model2", "model3", "model4"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Clovis",
		"divpics":"hello world 4",
		"qrcode": "website-model4",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0005",
		"firstname": "Model",
		"lastname": "5",
		"fullname": "Model 5",
		"image" : "model5",
		"showthumbnail": true,
		"thumbnail": ["model1", "model2", "model3", "model5"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Visalia",
		"divpics":"hello world 5",
		"qrcode": "website-model5",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0006",
		"firstname": "Model",
		"lastname": "6",
		"fullname": "Model 6",
		"image" : "model6",
		"showthumbnail": true,
		"thumbnail": ["model1", "model2", "model3", "model6"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 6",
		"qrcode": "website-model6",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0007",
		"firstname": "Model",
		"lastname": "7",
		"fullname": "Model 7",
		"image" : "model7",
		"showthumbnail": true,
		"thumbnail": ["model7","model5"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 7",
		"qrcode": "website-model7",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0008",
		"firstname": "Model",
		"lastname": "8",
		"fullname": "Model 8",
		"image" : "model8",
		"showthumbnail": true,
		"thumbnail": ["model8"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 8",
		"qrcode": "website-model8",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0009",
		"firstname": "Model",
		"lastname": "9",
		"fullname": "Model 9",
		"image" : "model9",
		"showthumbnail": true,
		"thumbnail": ["model9"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 9",
		"qrcode": "website-model9",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0010",
		"firstname": "Model",
		"lastname": "10",
		"fullname": "Model 10",
		"image" : "model10",
		"showthumbnail": true,
		"thumbnail": ["model10"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 10",
		"qrcode": "website-model10",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0011",
		"firstname": "Model",
		"lastname": "11",
		"fullname": "Model 11",
		"image" : "model11",
		"showthumbnail": true,
		"thumbnail": ["model11"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 11",
		"qrcode": "website-model11",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0012",
		"firstname": "Model",
		"lastname": "12",
		"fullname": "Model 12",
		"image" : "model12",
		"showthumbnail": true,
		"thumbnail": ["model12"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 12",
		"qrcode": "website-model12",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0013",
		"firstname": "Model",
		"lastname": "13",
		"fullname": "Model 13",
		"image" : "model13",
		"showthumbnail": true,
		"thumbnail": ["model13"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 13",
		"qrcode": "website-model13",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0014",
		"firstname": "Model",
		"lastname": "14",
		"fullname": "Model 14",
		"image" : "model14",
		"showthumbnail": true,
		"thumbnail": ["model14"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 14",
		"qrcode": "website-model14",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0015",
		"firstname": "Model",
		"lastname": "15",
		"fullname": "Model 15",
		"image" : "model15",
		"showthumbnail": true,
		"thumbnail": ["model15"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 15",
		"qrcode": "website-model15",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0016",
		"firstname": "Model",
		"lastname": "16",
		"fullname": "Model 16",
		"image" : "model16",
		"showthumbnail": true,
		"thumbnail": ["model16"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 16",
		"qrcode": "website-model16",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0017",
		"firstname": "Model",
		"lastname": "17",
		"fullname": "Model 17",
		"image" : "model17",
		"showthumbnail": true,
		"thumbnail": ["model17"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 17",
		"qrcode": "website-model17",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0018",
		"firstname": "Model",
		"lastname": "18",
		"fullname": "Model 18",
		"image" : "model18",
		"showthumbnail": true,
		"thumbnail": ["model18"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 18",
		"qrcode": "website-model18",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0019",
		"firstname": "Model",
		"lastname": "19",
		"fullname": "Model 19",
		"image" : "model19",
		"showthumbnail": true,
		"thumbnail": ["model19"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 19",
		"qrcode": "website-model19",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0020",
		"firstname": "Model",
		"lastname": "20",
		"fullname": "Model 20",
		"image" : "model20",
		"showthumbnail": true,
		"thumbnail": ["model20"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 20",
		"qrcode": "website-model20",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	},
	{
		"id" : "0021",
		"firstname": "Model",
		"lastname": "21",
		"fullname": "Model 21",
		"image" : "model21",
		"showthumbnail": true,
		"thumbnail": ["model21"],
		"imagerotator": ["bannerad5", "bannerad", "bannerad2", "bannerad3"], 
        "linkimage":["http://www.google.com","http://www.yahoo.com","http://www.bing.com","http://www.google.com"],
		"dob" : "NA",
		"team": "NA",
		"position": "NA",
		"city": "Fresno",
		"divpics":"hello world 21",
		"qrcode": "website-model21",
		"paragraph1": "THis is a Test, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph2": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought.",
		"paragraph3": "Lord Ipsum, Yo is a model from the country of Zimbabwe in Africa. asdkf laksjdfljasdkfl;j alksdjf alkjsdf  Lord Ipsum, imigrated to the Uto win the war tha alksdjf l asdfl asdlfka sdfkasdfj klasjdflkja sdkfja ksldjf akljsdfasdf asdfasdfasdf asdf sadf ajsdf lkajlksdf jalksjd ft is being fought."
	}

]